apps/semi_restful_app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.view,  name='view'),
    url(r'^new/$', views.new,  name='new'),
    url(r'^create/$', views.create,  name='create'),
    url(r'^(?P<show_id>\d+)/edit/$', views.edit, name="edit"),
    url(r'^(?P<show_id>\d+)/update/$', views.update, name="update"),
    url(r'^(?P<show_id>\d+)/$', views.display, name="display"),
]

semi_restful_proj/urls.py
from django.conf.urls import url, include
# from django.contrib import admin

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^shows/', include('apps.semi_restful_app.urls',  namespace='shows')),
]

apps/semi_restful_app/models.py
from django.db import models
from datetime import datetime, timedelta
# Create your models here.

class ShowManager (models.Manager):
    def validate(self, form):
        errors = []
        if len(form['title']) < 1:
            errors.append("Title  must not be blank.")
        
        if len(form['network']) < 1:
             errors.append("Network must not be blank.")
        
        if len(form['description']) < 1:
             errors.append("Description must not be blank.")
        try:
            # if this doesn't work, it will throw an error
            # if there's an error we'll use the except block
            release_date = datetime.strptime(form['release_date'], '%Y-%m-%d')
            now = datetime.now()
            if release_date > now:
                errors.append("Release Date must be in the past.")
        except:
            # date input works in chrome and takes this pattern
            # the date input sends a different pattern back, hence the strptime formatting
            errors.append("release_date must be a valid date in MM/DD/YYYY format.")
        
        return errors
    
    def easy_show_create (self, form):
        show = Show.objects.create(
            title = form['title'],
            network = form['network'],
            release_date = form['release_date'],
            description = form['description'],
        )
        return show.id
        
    def easy_show_update (self, form, show_id):
        show = Show.objects.filter(id=show_id)
        show.title = form['title'],
        show.network = form['network'],
        show.release_date = form['release_date'],
        show.description = form['description'],
        show.save()
        
        
class Show(models.Model):
    title = models.CharField(max_length=30)
    network = models.CharField(max_length=30)
    release_date = models.DateTimeField()
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = ShowManager()

    def __repr__(self):
        return f"<Show id:{self.id}>"

    def __str__(self):
        return f"<Show id:{self.id}>"

apps/semi_restful_app/views.py
from django.shortcuts import render, redirect
from .models import Show
from django.contrib import messages

# Create your views here.

def  new (request):
     return render ( request, 'index.html')


def create (request):
     errors = Show.objects.validate(request.POST)
     if errors:
        for error in errors:
             messages.error(request, error)
        return render(request,'index.html')
     else:
        show_id = Show.objects.easy_show_create (request.POST)
        return redirect('/shows/' + str(show_id))
   
   

def view(request):
    context = {
        "all_shows": Show.objects.all(),
    }
    return render(request, 'shows.html', context)

    
def edit (request, show_id):
    context = { 
         "show" : Show.objects.get(id=show_id),
    }
    return render (request, 'edit.html', context)

def update(request, show_id):
    show = Show.objects.easy_show_update (request.POST, show_id)
    return redirect ('/shows/new/')

def display(request, show_id):
    context = {
        "show": Show.objects.get(id=show_id),
    }
    return render(request, 'views.html', context)

apps/semi_restful_app/templates/edit.html
<h1>Edit Show {{show.id}} </h1>
<form action="{%  url 'shows:update' show.id%}" method="POST">
    {% csrf_token %}
    <p>title: <input type="text" name="title" value="{{show.title}}"></p>
    <p>network: <input type="text" name="network" value="{{show.network}}"></p>
    <p>release_date: <input type="date" name="release_date" value="{{show.release_date}}"></p>
    <input type="submit" value="update">
</form>

apps/semi_restful_app/templates/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Document</title>
    </head>
    <body>
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
                    {{ message }}
                </li>
                {% endfor %}
            </ul>
            {% endif %}
        <h1>Semi_Restful_app</h1>
        <h2>Add a new show</h2>
        <form action="{% url 'shows:create' %}" method="POST">
            {%csrf_token%}
            <p><input type="text" name="title" placeholder="Walking Dead"></p>
            <p><input type="text" name="network" placeholder="NBC"></p>
            <p><input type="date" name="release_date"></p>
            <p><textarea name="description" id="" cols="30" rows="10" placeholder="Show description goes here"></textarea></p>
            <input type="submit" value="create">
        </form>
    </body>
</html>

apps/semi_restful_app/templates/shows.html
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Document</title>
    </head>
    
    <body>
        <table>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Title</th>
                    <th>Network</th>
                    <th>Release Date</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for show in all_shows %}
                <tr>
                        <td>{{show.id}}</td>
                        <td>{{show.title}}</td>
                        <td>{{show.network}}</td>
                        <td>{{show.release_date}}</td>

                        <td><a href="/shows/{{show.id}}">Show</a> <a href="/shows/{{show.id}}/edit">Edit</a> <a href="">Delete</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </body>
</html>

apps/semi_restful_app/templates/views.html
<h1>TV Show {{show.id}}</h1> <a href="/shows/new">Go back</a> 
<div class="shows">
    <p>{{show.title}}</p>
    <p>{{show.network}}</p>
    <p>{{show.release_date}}</p>
    <p>{{show.description}}</p>
</div>